version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest test.py

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      # Add deployment job here if needed
      # - deploy:
      #     requires: - build-and-test  
      #     filters:
      #       branches:
      #         only:
      #           - main